#!/usr/bin/env python3
"""
Quick Hugging Face Token Setup
Set up the provided token directly
"""

import os
import sys
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))

def setup_token():
    """Set up the Hugging Face token"""
    print("🤗 Setting up Hugging Face token...")
    
    # Get token from user input
    token = input("Please enter your Hugging Face token: ").strip()
    
    if not token:
        print("❌ No token provided")
        return False
    
    print(f"Token: {token[:8]}...")
    
    # Set environment variables
    os.environ['HUGGINGFACE_TOKEN'] = token
    os.environ['HF_TOKEN'] = token
    
    # Create .env file
    env_file = Path(__file__).parent.parent / '.env'
    with open(env_file, 'w') as f:
        f.write("# Hugging Face Configuration\n")
        f.write("# Generated by setup_token.py\n\n")
        f.write(f"HUGGINGFACE_TOKEN={token}\n")
        f.write(f"HF_TOKEN={token}\n")
    
    print(f"✅ Token saved to {env_file}")
    
    # Test the token
    try:
        from huggingface_hub import login, whoami
        login(token=token)
        user = whoami()
        print(f"✅ Successfully logged in as: {user}")
        return True
    except Exception as e:
        print(f"❌ Error testing token: {e}")
        return False

if __name__ == "__main__":
    setup_token() 